apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-workflow-merge
spec:
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: dev
                matchExpressions:
                  - key: cluster
                    operator: NotIn
                    values:
                      - vcluster-10
              values:
                path: argo-workflow/3.2.4
          - clusters:
              selector:
                matchLabels:
                  bu: ip
              values:
                path: argo-workflow/3.2.0
          - list:
              elements:
                - name: vcluster-15
                  url: ''
                  values:
                    path: argo-workflow/3.2.6
  template:
    metadata:
      name: 'argo-workflow-me-{{name}}'
      labels:
        appset: argo-workflow-merge
        env: '{{metadata.labels.env}}'
      annotations:
        version: '{{values.path}}'
    spec:
      project: argo-workflow
      source:
        helm:
          fileParameters:
            - path: values.yaml
        repoURL: 'https://github.com/vgunapati-demo/argo-workflow.git'
        targetRevision: HEAD
        path: '{{values.path}}'
      destination:
        name: '{{name}}'
        namespace: workflow
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - PrunePropagationPolicy=foreground
          - CreateNamespace=true
          - PruneLast=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
